name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: your-google-cloud-project-id
        service_account_key: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        export_default_credentials: true

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/your-google-cloud-project-id/your-app-name:$GITHUB_SHA .

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/your-google-cloud-project-id/your-app-name:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy your-service-name \
          --image gcr.io/your-google-cloud-project-id/your-app-name:$GITHUB_SHA \
          --region your-region \
          --platform managed \
          --allow-unauthenticated

