name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: kai-new-feature
        service_account_key: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        export_default_credentials: true

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
    
    - name: Get Secrets from Google Cloud Secrets Manager
      id: secrets
      uses: google-github-actions/get-secretmanager-secrets@v2
      with:
        secrets: |
          GOOGLE_API_KEY:projects/kai-new-feature/secrets/GOOGLE_API_KEY/versions/latest
          PROJECT_ID:projects/kai-new-feature/secrets/PROJECT_ID/versions/latest
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t gcr.io/kai-new-feature/kai-backend-service:$GITHUB_SHA .
        docker tag gcr.io/kai-new-feature/kai-backend-service:$GITHUB_SHA gcr.io/kai-new-feature/backend-service:latest

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/kai-new-feature/kai-backend-service:$GITHUB_SHA
        docker push gcr.io/kai-new-feature/kai-backend-service:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy kai-api \ 
          --image gcr.io/kai-new-feature/kai-backend-service:$GITHUB_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_API_KEY=${{ steps.secrets.outputs.GOOGLE_API_KEY }} \
          --set-env-vars PROJECT_ID=${{ steps.secrets.outputs.PROJECT_ID }}
          --memory=512Mi \
          --concurrency=80 \
          --max-instances=10
          